<?php

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * Primary module hooks for Security Pack module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_help().
 */
function security_pack_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.security_pack':
            $text = file_get_contents(__DIR__ . '/README.md');
            if (!Drupal::moduleHandler()->moduleExists('markdown')) {
                return '<pre>' . Html::escape($text) . '</pre>';
            }
            else {
                // Use the Markdown filter to render the README.
                $filter_manager = Drupal::service('plugin.manager.filter');
                $settings = Drupal::configFactory()->get('markdown.settings')->getRawData();
                $config = ['settings' => $settings];
                $filter = $filter_manager->createInstance('markdown', $config);
                return $filter->process($text, 'en');
            }
    }
    return NULL;
}